packages:
  - packages/*

catalog:
  "@ai-devkit/memory": ^0.5.0
  "@types/node": ^24
  "@vee-validate/zod": ^4.15.1
  "@vueuse/core": ^14.2.1
  reka-ui: ^2.8.2
  typescript: ^5
  vee-validate: ^4.15.1
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zod: ^4.3.6

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
